##开启调试
debug: false

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.15.104:3306/db_exhibition?useUnicode=true&characterEncoding=utf8
    username: xungeng
    password: 15xungeng!@%

##内置tomcat配置
##server:
##  port: 8084
##自定义常量
myYml:
  moduleApiHost: http://192.168.15.111:8080/frame_module/apiInfo/url
  totalNumber: 10