spring:
  application:
    ###服务别名
    name: order-service
  cloud:
    nacos:
      discovery:
        ##注册中心地址
        server-addr: 192.168.9.225:8848
  datasource:
    url: jdbc:mysql://192.168.9.225:3306/db_ljlj?useSSL=false&useUnicode=true&characterEncoding=latin1&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #connectionInitSqls:
    #druid:
    #  connection-init-sqls: set names latin1 #物理连接初始化的时候执行的sql

server:
  port: 8098


#ribbon, SpringCloud feign 默认开启支持ribbon负载均衡
ribbon:
  #说明：使用Apache HttpClient请求连接超时时间，单位为毫秒
  ConnectTimeout: 1000
  #说明：使用Apache HttpClient请求处理超时时间，单位为毫秒
  ReadTimeout: 1000
  #说明：同一台实例的最大自动重试次数，默认为1次，不包括首次
  MaxAutoRetries: 1
  #说明：要重试的下一个实例的最大数量，默认为1，不包括第一次被调用的实例
  MaxAutoRetriesNextServer: 1
  #说明：是否所有的操作都重试，默认为true,为false时GET请求方式也会进行重试，非GET方法只有在连接异常时才会进行重试
  OkToRetryOnAllOperations: false
  #说明：从注册中心刷新服务器列表信息的时间间隔，默认为2000毫秒，即2秒
  ServerListRefreshInterval: 2000


### feign　客户端配置
feign:
  hystrix:
    enabled: false #开启或关闭hystrix熔断器
#hystrix配置，只有在feign.hystrix.enable:true 开启的时候才会起作用
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #客户端请求服务端服务器端超时时间10s，默认1s
#日志配置文件
logback:
  #日志路径
  logdir: logs
  #日志文件名
  appname: order-log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
  mapper-locations: classpath:mappers/*.xml #扫描mapper对应dao包
    #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql语句打印
  #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl #关闭sql语句打印
  global-config:
    db-config:
      id-type: auto #主键策略为auto
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)

#####自定义属性####
ljconfig:
  mybatis:
    interceptor:
      query-enable: false #mybatis查询拦截器结果PO属性转码latin1为utf8,开关 (true/false)
      param-enable: false #mybatis参数拦截器，只对实体参数PO属性编码转换utf8为latin1,开关(true/false)

